notifications:
  slack:
    rooms:
    - splitap:Vnw3VIpk6kvUlap76ExiMYOA#build_status
    email: false
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository

before_script:

before_install:
  - openssl aes-256-cbc -K $encrypted_b8711ceb9a5c_key -iv $encrypted_b8711ceb9a5c_iv -in app/google-services.json.enc -out app/google-services.json -d

script:
  - ./gradlew build --continue

after_success:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
